docstring for data generation function
UBC-MDS/lr_cd pull request #7
Opened 2024-01-11 00:47 UTC by fohy24

Hey this is the docstring for the data generation function. Please take a look!

2024-01-11 03:51 UTC, andyzhangstat commented
Hi Sam, your docstring looks good. But did you get the latest 'main' before pushing your branch? Your branch seems to 1 commit ahead of main, and  2 commits behind main.

2024-01-11 18:24 UTC, Jing-19 commented on src/lr_cd/lr_data_generation.py
> +    A dataframe containing the data points (X, y), where X is the randomly generated regressor values, and y is the corresponding binary target.
Please update the y to random continuous variables.

2024-01-11 18:59 UTC, Jing-19 commented on src/lr_cd/lr_data_generation.py
> +    An array containing the data points (X, y), where X is the randomly generated regressor values, and y is the corresponding continuous target.
Please update it to two 1D array

2024-01-11 21:19 UTC, Jing-19 commented
Looks good to me! thanks!

2024-01-11 21:19 UTC, Jing-19 approved these changes

2024-01-12 03:56 UTC, fohy24 commented
> Hi Sam, your docstring looks good. But did you get the latest 'main' before pushing your branch? Your branch seems to 1 commit ahead of main, and 2 commits behind main.

Merged with main branch just now. Should be good.

2024-01-12 04:36 UTC, andyzhangstat approved these changes

2024-01-12 04:36 UTC, andyzhangstat commented on src/lr_cd/lr_data_generation.py
> +    An array that returns X, the randomly generated regressor values, and another array containing y, the corresponding continuous target.
there are two items needs to be returned, one is X  and another one is y. Could you return them separately? sth like:
 Returns
    -------
    X : ndarray
        Feature data matrix of shape (n_samples, n_features).
    y : ndarray
        Response data vector of shape (n_samples,).

2024-01-12 04:36 UTC, andyzhangstat commented on src/lr_cd/lr_data_generation.py
> +    theta : float
The theta here should be a np array which contains the scalar intercept and coefficient weights vector. OR you can use two input arguments: intercept (float) and coeff (array). See the link below for more: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression

2024-01-12 04:36 UTC, andyzhangstat commented on src/lr_cd/lr_data_generation.py
> +    Returns
I think it may be necessary to include the true intercept and coefficients vector as return. Jing may use it for plotting.

2024-01-12 04:45 UTC, andyzhangstat requested changes
The input of function may contain the n, p(in our example is default 2) and seed, we don't need to specify the weights. The output of function may contain the X, y, and true intercept and true coefficient vector.

2024-01-12 04:56 UTC, Jing-19 commented on src/lr_cd/lr_data_generation.py
> +    An array that returns X, the randomly generated regressor values, and another array containing y, the corresponding continuous target.
I think X should be also one-dimensional. The column of ones should be added inside the fit function. But I agree that the return could be more detailed as what Andy suggests

2024-01-12 04:57 UTC, Jing-19 commented on src/lr_cd/lr_data_generation.py
> +    Returns
I only need the intercept and coefficients calculated from the fit function. X and y should be the only two outputs for this function?

2024-01-12 16:40 UTC, fohy24 commented
> The input of function may contain the n, p(in our example is default 2) and seed, we don't need to specify the weights. The output of function may contain the X, y, and true intercept and true coefficient vector.

Returning the true parameters from a set of randomly generated data requires fitting. It is what the fitting function is for.

2024-01-12 16:40 UTC, fohy24 commented on src/lr_cd/lr_data_generation.py
> +    An array that returns X, the randomly generated regressor values, and another array containing y, the corresponding continuous target.
fixed

2024-01-12 16:41 UTC, fohy24 commented on src/lr_cd/lr_data_generation.py
> +    theta : float
fixed

2024-01-12 19:37 UTC, andyzhangstat approved these changes

2024-01-12 19:43 UTC, merged